# Generated by Django 5.1.3 on 2024-11-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('last_price', models.FloatField()),
                ('market_cap', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stock_symbol', models.CharField(max_length=10)),
                ('crypto_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('last_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
